# all services
services:
  - type: web
    name: fuzo
    env: node
    repo: https://github.com/jycouet/fuzo
    region: frankfurt
    plan: Free
    branch: main
    buildCommand: npm i -g pnpm; pnpm install --production=false; pnpm build
    startCommand: pnpm start
    numInstances: 1
    envVars:
      - key: NODE_VERSION
        value: 18.14.2
      - key: TZ
        value: utc
      - key: NODE_ENV
        value: production
