name: Quality checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup node with version 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          run_install: true
          version: 7
      - name: Run linter
        run: pnpm run lint
      - name: Run Svelte Check
        run: pnpm run check
  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout sources
  #       uses: actions/checkout@v3
  #     - name: Setup node with version 18
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #         registry-url: 'https://registry.npmjs.org'
  #     - name: Install PNPM
  #       uses: pnpm/action-setup@v2
  #       with:
  #         run_install: true
  #         version: 7
  #     - name: Run test (Vitest)
  #       run: pnpm run test:unit --run
